# Generated by Django 6.0.5 on 2026-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('assignee_github_login', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('workflow_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('github_url', models.URLField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('ai_triage', models.JSONField(blank=True, null=True)),
                ('similar_issues', models.JSONField(blank=True, default=list)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_time_hours', models.FloatField(blank=True, null=True)),
                ('classified_team', models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('fullstack', 'Full Stack'), ('', '')], default='', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('low', 'Low'), ('', '')], default='', max_length=10)),
                ('severity_reason', models.CharField(blank=True, default='', max_length=500)),
                ('suggested_action', models.CharField(blank=True, default='', max_length=500)),
                ('estimated_complexity', models.CharField(blank=True, choices=[('quick-fix', 'Quick Fix'), ('medium', 'Medium'), ('complex', 'Complex'), ('', '')], default='', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
