# Generated by Django 6.0.5 on 2026-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
