# Generated by Django 6.0.5 on 2026-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_ai_explanation_issue_github_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
