# Generated by Django 6.0.6 on 2026-06-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_reminder'),
        ('users', '0002_remove_team_github_repo_remove_team_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='users.repository'),
        ),
    ]
