# Generated by Django 6.0.6 on 2026-06-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_issue_id'),
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('issue_id', 'repository')},
        ),
    ]
