# Generated by Django 6.0.6 on 2026-06-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='team',
            name='github_pat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_members', to='users.team'),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('invite_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='users.team')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.repository'),
        ),
    ]
